config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root to: 'store#index', as: 'store'
  get "store/index"
  resources :products  do
    get :who_bought, on: :member
  end

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pragprog Books Online Store
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{class: controller.controller_name}
    #banner
      = form_tag store_path, class: 'locale' do
        = select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()'
        = submit_tag 'submit'
        = javascript_tag "$('.locale input').hide()"
      = image_tag("logo.png")
      = @page_title || t('.title')
    #columns
      #side
        = hidden_div_if(@cart.line_items.empty?, id: 'cart') {render @cart} unless (current_page?(new_cart_path) || @cart.nil?)
        -##cart= render partial: 'carts/cart', object: @cart
        %ul
          %li= link_to t('.home'), store_path
          %li= link_to "Questions", "http://www..../faq"
          %li= link_to "News", "http://www..../news"
          %li= link_to "Contact", "http://www..../contact"
          = time_tag(Time.now)
          #counter= @counter_label
        - if session[:user_id]
          %ul
            %li= link_to 'Orders', orders_path
            %li= link_to 'Products', products_path
            %li= link_to 'Users', users_path
          = button_to 'Logout', logout_path, method: :delete
      #main
        = yield